### ISSUE TITLE
Ошибка в расчете расстояния

### ISSUE THREAD

**Issue by leSemaleon** [salsergey/gpxviewer#1]
Здравствуйте,
В программе на Windows похоже закралась ошибка. Соседними точками (маркерами) считаются точки идущие подряд при сортировке по названию, хотя логичнее было бы сделать соседними те, что идут подряд при сортировке по времени создания. Из-за этого график высот строится не верно.
Оба случая представлены на скриншотах
![pythonw_RQCcCbpzDK](https://github.com/salsergey/gpxviewer/assets/101531959/ad4d774b-8751-4520-81fa-d74f7622c8aa)
![pythonw_cl0prgit7J](https://github.com/salsergey/gpxviewer/assets/101531959/1a4616b8-959c-4191-9716-ec501b268ab2)

**Comment by salsergey** [comment]
Здравствуйте.
По умолчанию расстояние считается по порядку упоминания точек в gpx файле. Сортировку по времени при импорте можно включить в настройках на вкладке импорта.

**Comment by leSemaleon** [comment]
Понял, спасибо. Предполагаю, что BaseCamp после редактирования треков сохранил gpx таким образом, что все флаги встали в начало и в алфавитном порядке .
